In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier



In [ ]:
data = load_breast_cancer(as_frame=True).frame

ValueError: too many values to unpack (expected 2)

In [3]:
data

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0


In [4]:
data.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'target'],
      dtype='object')

In [7]:
data["target"].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [11]:
X,y = load_breast_cancer(return_X_y=True)

In [13]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [15]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.fit_transform(X_test)

In [16]:
X_test_scaler

array([[-0.20091317,  2.66240433, -0.22686155, ..., -0.59820681,
        -1.0307737 , -0.44558275],
       [-0.52778686, -0.87983632, -0.59305302, ..., -1.03959443,
        -0.89515356, -1.20333954],
       [ 0.73256263,  0.99348562,  0.80393335, ...,  1.58896545,
         2.46343928,  0.41819762],
       ...,
       [-0.84837451,  1.8447914 , -0.89010027, ..., -1.44234205,
        -0.16253889, -0.70752337],
       [ 1.75089988, -0.16105572,  1.7910582 , ...,  1.58747929,
         0.89317081,  0.24401602],
       [-0.86408959, -1.32682801, -0.8264148 , ...,  0.2068426 ,
         0.49428805,  0.2404522 ]])

In [17]:
X_train_scaler

array([[-0.77611594, -0.4294345 , -0.79139683, ..., -0.41088525,
         0.15544084, -0.34710553],
       [ 0.02656202,  0.64795173,  0.17287269, ...,  0.99197065,
        -0.06759189,  1.79510048],
       [-0.38727541, -1.4174306 , -0.39650167, ..., -0.45487778,
        -0.55169394, -0.04270255],
       ...,
       [-1.34965573, -1.29275491, -1.2962985 , ..., -0.63100119,
         1.37952745,  0.39412771],
       [-0.54836649,  0.26451515, -0.60079947, ..., -0.60509618,
        -0.32693228, -0.86662793],
       [-0.36227851,  0.46446674, -0.38280122, ..., -0.88560605,
        -0.68309307, -0.10382283]])

In [18]:
knn = KNeighborsClassifier()

knn.fit(X_train_scaler, y_train )

KNeighborsClassifier()

In [19]:
print(knn.score(X_test_scaler, y_test))

0.9473684210526315


In [20]:
knn.predict([])

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.